# Generated by Django 4.0.4 on 2022-05-20 16:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('food_app', '0002_userreview'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userreview',
            old_name='subject',
            new_name='location',
        ),
        migrations.RemoveField(
            model_name='userreview',
            name='rating',
        ),
    ]
