# Generated by Django 4.0.4 on 2022-05-20 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food_app', '0003_rename_subject_userreview_location_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userreview',
            name='subject',
            field=models.CharField(default=1, max_length=150),
            preserve_default=False,
        ),
    ]
