# Generated by Django 4.0.4 on 2022-05-20 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food_app', '0004_userreview_subject'),
    ]

    operations = [
        migrations.AddField(
            model_name='foodplace',
            name='active',
            field=models.BooleanField(default=True),
        ),
    ]
