# Generated by Django 4.0.4 on 2022-05-22 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food_app', '0006_alter_foodplace_rating'),
    ]

    operations = [
        migrations.AddField(
            model_name='foodplace',
            name='zomato_link',
            field=models.CharField(default=1, max_length=500),
            preserve_default=False,
        ),
    ]
