# Generated by Django 4.0.4 on 2022-05-22 21:12

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food_app', '0007_foodplace_zomato_link'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reviewrating',
            name='rating',
            field=models.FloatField(validators=[django.core.validators.MaxValueValidator(10.0)]),
        ),
    ]
